[package]
name = "violin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[features]
default = []
nightly = [] # Enable nighlty or experiemental features
doc     = [] # Used when compiling docs
std     = ["rand/std"] # Enable stdlib support
alloc   = ["rand/alloc"] # Enable heap allocations
