---
on: [push, pull_request]

name: Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.59.0 # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Spell Check
        uses: crate-ci/typos@master

      - name: Lint
        uses: m3y/rust-just-action@v1
        with:
          command: lint

      - name: Test
        uses: m3y/rust-just-action@v1
        with:
          command: test 'cargo test'
