---
on: [push, pull_request]

name: Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.59.0 # MSRV

    steps:
    - uses: actions/checkout@v2

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          pdrofile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: install just

      - uses: Spell Check
        run: just spell-check

      - uses: Lint
        run: just lint

      - uses: Test
        run: just test
